version: "3.2"
services:
  wordpress:
    image: wordpress
    networks:
    - wordpress
    ports:
    - 8080:80
    environment:
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_USER=adam
    - WORDPRESS_DB_PASSWORD=admin
    - WORDPRESS_DB_NAME=test
    depends_on:
    - mysql

  mysql:
    image: mysql
    networks:
    - wordpress
    ports:
    - 3306:3306
    volumes:
    -  mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    - MYSQL_USER=adam
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=test

networks:
 wordpress:
    driver: bridge
volumes:
 mysql_data:
    driver: local
